/**
 * Copy for the aircraft-request pages (/send, /request, /confirm, /clubs), EN and FR.
 *
 * In one module rather than in each component because the pages' scripts need most of it too: the
 * components render what they can at build time and hand the rest to their script as JSON. Tokens in
 * braces ({reg}, {name}…) are filled by `fill()`. French follows the site's typography (a plain space
 * before : ; ? !, guillemets « »).
 */
import type { Lang } from './site';

export function fill(text: string, values: Record<string, string | number>): string {
  return text.replace(/\{(\w+)\}/g, (all, key: string) => (key in values ? String(values[key]) : all));
}

const en = {
  common: {
    support: 'Support',
    supportHref: '/support',
    retry: 'Try again',
    backToForm: 'Back to the form',
    code: 'Code:',
    loading: 'Loading',
    otherLang: 'Cette page en français',
    privacyHref: '/privacy',
    termsHref: '/terms',
    clubsHref: '/clubs',
    sendHref: '/send',
    aircraftHref: '/aircraft',
    dash: 'none',
  },
  errors: {
    network: 'The request service isn’t answering. Check your connection and try again; if it still fails, the service may be down for a while.',
    invalid_json: 'The service couldn’t read what the page sent. Reload the page and try again.',
    invalid_field: 'One of the fields wasn’t accepted: it is marked in the form.',
    invalid_registration: 'That doesn’t read as a registration. Type it as it’s painted on the aircraft: HB-KFD, F-HVXA, D-EABC.',
    invalid_email: 'That e-mail address doesn’t look right.',
    club_contact_is_sender: 'The club’s contact can’t be your own address: someone else at the club confirms. If you look after the club’s documents yourself, send it “For the club”.',
    rights_required: 'Tick that you may share this document.',
    privacy_required: 'Tick that you have read how what you send is kept.',
    too_many_files: 'Up to 4 files: remove one, then send again.',
    bad_type: 'One of the files isn’t a PDF, JPEG, PNG or HEIC: remove it, then send again.',
    file_too_large: 'One of the files is over 10 MB: remove it, or send a smaller copy.',
    total_too_large: 'The files come to more than 25 MB in all: remove one, or send smaller copies.',
    unknown_registration: 'AéroCheck doesn’t have this registration (any more), so it can’t be an update. The form now sends it as a new aircraft: check its details, then send again.',
    known_registration: 'AéroCheck already has this registration, so this is an update. The form has switched to it: check, then send again.',
    size_mismatch: 'A file changed while it was being sent (its size isn’t the one the form announced). Choose it again, then send again.',
    turnstile_failed: 'The check that you’re not a robot didn’t go through. It has started again: wait for it to finish, then send again.',
    not_found: 'This link doesn’t open anything. Copy it again from the e-mail, whole (the part after # matters); the request may also have been closed and deleted.',
    missing_files: 'Not every file arrived. Try again: they are sent once more.',
    wrong_state: 'This has changed in the meantime: the page now shows it as it is.',
    length_required: 'Your browser sent a file without its size, which the service needs. Try again in another browser (or an updated one).',
    payload_too_large: 'The form is too long for the service (the notes, most likely). Shorten it, then send again.',
    bad_file: 'One of the files isn’t what its name says (its content isn’t a PDF, JPEG, PNG or HEIC). Remove it, then send again.',
    rate_limited: 'Too many tries from your connection in a short time. Wait a minute, then try again.',
    internal: 'The service ran into a problem on its side. Try again in a moment; if it keeps happening, write to us.',
    unavailable: 'Requests are closed for the moment (the service isn’t ready). Try again later: nothing was sent.',
    daily_cap: 'That’s all the requests we can take today. Try again tomorrow: nothing was sent.',
    lookup_unavailable: 'AéroCheck’s aircraft list can’t be read right now, so the registration can’t be checked. Try again in a few minutes.',
    forbidden: 'This link isn’t valid (any more). Copy it again from the e-mail, whole.',
    unknown: 'Something went wrong.',
    noToken: 'This page opens with the link from your e-mail (it ends with #t= and a long code). Open that link again.',
    uploadGone: 'This sending has expired (files wait 24 hours at most) or its link is wrong. Send the request again.',
    alreadySent: 'This request was sent already: {ticket}. Its link is in the e-mail we sent you.',
    contactClosed: 'The club’s contact can’t be added any more (it was added already, or the request has moved on). The page now shows where it stands.',
    proofClosed: 'The draft isn’t open for proofreading any more: the request has moved on.',
    listChanged: 'AéroCheck’s aircraft list changed while you filled in the form. Look the registration up again in a few minutes, then send.',
  },
  statuses: {
    uploading: { label: 'Incomplete', line: 'The files never finished uploading, so this request was never sent.' },
    received: { label: 'Received', line: 'We have your request and its files. Next, we decide whether (and when) we add it.' },
    accepted: { label: 'Accepted', line: 'The checklist will be added to AéroCheck.' },
    converting: { label: 'In preparation', line: 'The checklist is being prepared for AéroCheck.' },
    proofreading: { label: 'Proofreading', line: 'A draft is ready. Have a look below if you have five minutes (it’s optional).' },
    testflight: { label: 'In testing', line: 'The checklist is in the test version of the app. The App Store version comes next.' },
    live: { label: 'Live', line: 'The aircraft is in AéroCheck, for AéroCheck Pro subscribers.' },
    'need-info': { label: 'Need info', line: 'We need something from you: see the message in the history, and reply to our e-mail.' },
    declined: { label: 'Declined', line: 'We won’t add this one. The reason is in the history.' },
    duplicate: { label: 'Duplicate', line: 'Someone already asked for this aircraft: that request carries on, this one is closed.' },
  } as Record<string, { label: string; line: string }>,
  club: {
    heading: 'The club’s OK',
    states: {
      'not-needed': 'Sent for the club: no confirmation needed.',
      pending: 'Waiting for the club’s confirmation. Nothing goes live without it.',
      confirmed: 'The club confirmed.',
      refused: 'The club said no: this aircraft won’t be added.',
    } as Record<string, string>,
    addLead: 'Add the club’s contact, and we send them the link to confirm.',
    addLabel: 'The club’s contact (e-mail)',
    addHint: 'Someone who can speak for the club about its documents (the president, the chief flying instructor, the technical manager). We send them a link to confirm or refuse, nothing else.',
    addButton: 'Send them the link',
    addDone: 'Sent: the club’s contact has the link.',
    addRequired: 'Give the club’s contact.',
    addInvalid: 'That e-mail address doesn’t look right.',
    addIsSender: 'That’s your own address: the club’s contact is someone else at the club, who confirms for it.',
  },
  kinds: { new: 'New aircraft', update: 'Checklist update' } as Record<string, string>,
  phases: {
    preflight: 'Preflight', beforeEngineStart: 'Before Engine Start', engineStart: 'Engine Start',
    afterEngineStart: 'After Engine Start', taxi: 'Taxi', runup: 'Run Up', beforeDeparture: 'Before Departure',
    lineUp: 'Line Up', climb: 'Climb', cruise: 'Cruise', descent: 'Descent', approach: 'Approach',
    landing: 'Landing', afterLanding: 'After Landing', shutdown: 'Engine Shutdown', hangar: 'At the Hangar',
  } as Record<string, string>,
  units: { kB: 'kB', MB: 'MB' },

  send: {
    eyebrow: 'Aircraft requests',
    title: 'Send an aircraft’s checklist',
    intro: 'Your aircraft isn’t in AéroCheck, or its checklist is older than the club’s? Send us the club’s document: once the club confirms, the aircraft joins the app (as part of AéroCheck Pro, like every aircraft but the WT9).',
    clubsLead: 'For flying clubs:',
    clubsLink: 'what to send, who sees it, and the club’s confirmation',
    stepRegistration: 'The registration',
    regLabel: 'Registration',
    regHint: 'As painted on the aircraft: HB-KFD, F-HVXA, D-EABC. AéroCheck checks whether it already has it.',
    regButton: 'Look it up',
    regChecking: 'Looking it up',
    knownTitle: '{reg} is already in AéroCheck',
    knownBody: 'This becomes an update: send the club’s new revision, and it replaces the checklist the app has.',
    knownModel: 'Aircraft',
    knownClub: 'Club',
    knownVersion: 'Current version',
    knownLanguages: 'Languages',
    unknownTitle: '{reg} isn’t in AéroCheck yet',
    unknownBody: 'This becomes a new aircraft. Tell us what it is, and send its checklist.',
    stepAircraft: 'The aircraft',
    otherRegsLabel: 'Other registrations with the same checklist (optional)',
    otherRegsHint: 'The club’s other aircraft of this type, if the same document covers them: HB-KFI, HB-KFO. Up to 10 registrations in all.',
    typeLabel: 'Aircraft type',
    typeHint: 'Manufacturer and model, as the club calls it: Robin DR400/180, Piper PA-28-181.',
    clubLabel: 'Flying club or operator (optional)',
    clubHint: 'Leave it empty for a privately owned aircraft.',
    stepSender: 'Who sends it',
    sendingForLegend: 'You send it',
    forClub: 'For the club',
    forClubHint: 'I look after the club’s documents, or the club asked me to send it.',
    forSelf: 'As a pilot',
    forSelfHint: 'I fly it. The club is asked to confirm before anything goes live.',
    contactLabel: 'The club’s contact (e-mail)',
    contactHint: 'Someone who can speak for the club about its documents (the president, the chief flying instructor, the technical manager). We send them a link to confirm or refuse, nothing else.',
    contactUnknown: 'I don’t know it: I’ll add it later from the request’s page',
    contactUnknownHint: 'The request then waits for the club’s OK until someone adds it.',
    stepChecklist: 'The checklist',
    filesLabel: 'The club’s checklist',
    filesHintNew: 'A PDF, or photos of its pages (JPEG, PNG or HEIC): up to 4 files, 10 MB each, 25 MB in all. Black out anything personal first (names, phone numbers).',
    filesHintUpdate: 'The new revision, as a PDF or photos of its pages (JPEG, PNG or HEIC): up to 4 files, 10 MB each, 25 MB in all.',
    filesChoose: 'Choose files',
    filesDrop: 'or drop them here',
    filesRemove: 'Remove',
    filesRemoveLabel: 'Remove {name}',
    filesTotal: '{n} of 4 files · {size} of 25 MB',
    languagesLegend: 'The checklist’s language',
    languagesHint: 'The language the document is written in. The checklist keeps it: it doesn’t follow the app’s language (English or French), so a German checklist reads in German in both.',
    otherLanguageLabel: 'Another language',
    otherLanguageNone: 'None',
    stepYou: 'You',
    nameLabel: 'Your name (optional)',
    nameHint: 'So the club knows who asked, if it’s asked to confirm.',
    emailLabel: 'Your e-mail',
    emailHint: 'We write to you here about this request (received, questions, when it’s live), and about nothing else.',
    notesLabel: 'Anything we should know (optional)',
    notesHint: 'Which pages are the checklist, what changed in this revision, an aircraft that differs from the others.',
    counter: '{n} / {max}',
    rightsClub: 'I may share this document with AéroCheck for the club, and it’s the club’s current revision as far as I know.',
    rightsSelf: 'I may share this document with AéroCheck, and it’s the club’s current revision as far as I know. The club will be asked to confirm.',
    rightsPrivate: 'The aircraft is mine (or its owner agrees), and I may share this document with AéroCheck.',
    rightsMore: 'What this means:',
    rightsLink: 'terms of use, section 4.0',
    termsAnchor: '#40-sending-us-an-aircrafts-checklist',
    privacyLabel: 'I have read how AéroCheck keeps and uses what I send:',
    privacyLink: 'privacy policy, section 4.3',
    privacyAnchor: '#43-aircraft-requests-intakeaerocheckapp',
    turnstileLabel: 'A quick check that you’re not a robot',
    turnstileLoading: 'Loading the check',
    turnstileFailed: 'The check couldn’t load (a content blocker, or Cloudflare can’t be reached). Reload the page to try again.',
    turnstileMissing: 'Wait for the check above to finish, then send.',
    notOpen: 'Requests aren’t open yet. Come back soon.',
    submit: 'Send the request',
    progressSending: 'Sending the request',
    progressUpload: 'Uploading {i} of {n}: {name}',
    progressFinishing: 'Finishing',
    progressLabel: 'Upload progress',
    uploadStopped: 'The upload stopped at {name}. Try again: the files already sent stay.',
    summary: 'Check these before sending:',
    fieldErrors: {
      regRequired: 'Type the registration, then look it up.',
      regLookup: 'Look up the registration first.',
      otherRegsInvalid: 'These don’t read as registrations: {list}.',
      tooManyRegs: 'Up to 10 registrations in all.',
      typeRequired: 'Say what aircraft it is.',
      sendingForRequired: 'Say whether you send it for the club or as a pilot.',
      contactRequired: 'Give the club’s contact, or tick that you don’t know it.',
      contactInvalid: 'That e-mail address doesn’t look right.',
      emailRequired: 'Give your e-mail: it’s where we tell you what happens.',
      emailInvalid: 'That e-mail address doesn’t look right.',
      languagesRequired: 'Pick the checklist’s language.',
      filesRequired: 'Add the checklist (a PDF or photos of its pages).',
      tooManyFiles: 'Up to 4 files: remove one first.',
      fileTooBig: '{name} is {size}: a file can be 10 MB at most.',
      fileEmpty: '{name} is empty.',
      fileType: '{name} isn’t a PDF, JPEG, PNG or HEIC.',
      fileContent: '{name} doesn’t look like the {type} its name says it is.',
      fileDuplicate: '{name} is already in the list.',
      knownOthers: 'Remove from this list: {list} (already in AéroCheck; a new revision is a request of its own).',
      totalTooBig: 'The files come to {size}: 25 MB at most in all.',
      notesTooLong: 'Keep it to 1,000 characters.',
      rightsRequired: 'Tick that you may share this document.',
      privacyRequired: 'Tick that you have read how what you send is kept.',
      field: 'The service didn’t accept this: check it.',
      fieldNamed: '{label}: the service didn’t accept it.',
    } as Record<string, string>,
    resultTitle: 'Sent: {ticket}',
    resultBody: 'We have your request. This link is how you follow it (we also sent it to {email}): keep it, it’s the only way in.',
    resultLink: 'Your request’s page',
    resultCopy: 'Copy the link',
    resultCopied: 'Copied',
    nextTitle: 'What happens next',
    nextBody: 'We look at it, then prepare it, which takes as long as it takes (one person, spare time, no promised date). You get an e-mail at each step that needs one, and the page always shows where it stands.',
    nextClub: 'The club’s contact has an e-mail asking them to confirm. Nothing goes live without it.',
    nextClubNoContact: 'The club hasn’t been asked yet: add its contact from the request’s page when you have it.',
    another: 'Send another aircraft',
  },

  status: {
    eyebrow: 'Aircraft request',
    title: 'Your request',
    loading: 'Loading the request',
    labelRegistrations: 'Registrations',
    labelAircraft: 'Aircraft',
    labelClub: 'Club',
    labelSent: 'Sent',
    labelUpdated: 'Last change',
    stepsHeading: 'Where it stands',
    stepDone: 'done',
    stepCurrent: 'now',
    stepSkipped: 'skipped',
    stepNext: 'to come',
    historyHeading: 'History',
    noTimeline: 'No date is promised: one person prepares the checklists, in their spare time. You get an e-mail when something needs you, and when it’s live.',
    proofHeading: 'Proofread the draft (optional)',
    proofIntro: 'Here is the checklist as the app will show it. Five minutes with the club’s document next to it is plenty: does each phase have its items, in order, with the right values? It’s a draft: never fly with it.',
    proofLoading: 'Loading the draft',
    proofFailed: 'The draft couldn’t be loaded.',
    proofPhases: 'Phases',
    proofSpeeds: 'Speeds',
    proofSpeedCols: ['Code', 'Description', 'Value'],
    proofCrosswind: 'Crosswind limits: take-off {takeoff}, landing {landing}',
    proofEmptyPhase: 'Nothing in this phase.',
    proofPage: 'p. {n}',
    proofVersion: 'Version {v}',
    verdictLegend: 'Your verdict',
    verdictOk: 'Looks right',
    verdictIssue: 'Something’s wrong',
    verdictMessage: 'What’s wrong, or anything to add',
    verdictHint: 'Name the phase and the item, and what the club’s document says instead.',
    verdictRequired: 'Say what’s wrong: the phase, the item, and what the document says.',
    verdictTooLong: 'Keep it to 2,000 characters.',
    verdictThanksOk: 'Thanks: noted as right.',
    verdictThanksIssue: 'Thanks: we’ll look at it and correct the draft.',
    proofYours: 'Your verdict so far: {verdict}. Send another below if something changes.',
    eventClub: {
      pending: 'The club was asked to confirm',
      confirmed: 'The club confirmed',
      refused: 'The club refused',
      'not-needed': 'No confirmation needed from the club',
    } as Record<string, string>,
    eventProofread: {
      ok: 'Your proofreading: looks right',
      issue: 'Your proofreading: something’s wrong',
    } as Record<string, string>,
  },

  confirm: {
    eyebrow: 'Flying clubs',
    title: 'Confirm a checklist request',
    loading: 'Loading the request',
    intro: '{sender} asked to add {club}’s checklist to AéroCheck for the aircraft below. As someone who can speak for the club, you decide whether it goes ahead.',
    introNoClub: '{sender} asked to add this checklist to AéroCheck for the aircraft below. As someone who can speak for the club, you decide whether it goes ahead.',
    senderUnknown: 'A pilot',
    labelTicket: 'Request',
    labelKind: 'What',
    labelRegistrations: 'Registrations',
    labelAircraft: 'Aircraft',
    labelClub: 'Club',
    labelLanguages: 'Checklist language',
    labelSent: 'Sent',
    whatTitle: 'What confirming means',
    what: [
      'AéroCheck may add the club’s checklist for these aircraft to the app, as part of AéroCheck Pro (like every aircraft but the free WT9).',
      'The document itself is never published: it is only used to prepare the checklist, and deleted 90 days after the request closes.',
      'In the app, the club’s approved checklist remains the reference.',
      'If the club later wants it withdrawn, it writes to us.',
    ],
    refuseBody: 'Refusing closes the matter: nothing is published, and the sender is told.',
    moreLead: 'More for clubs:',
    moreLink: 'aerocheck.app/clubs',
    decisionLegend: 'The club’s answer',
    confirm: 'Confirm: AéroCheck may add it',
    refuse: 'Refuse: don’t add it',
    nameLabel: 'Your name',
    roleLabel: 'Your role in the club',
    roleHint: 'President, chief flying instructor, technical manager, secretary.',
    messageLabel: 'A message for the sender and for us (optional)',
    statement: 'By answering, you state that you may speak for the club on this.',
    submit: 'Send the club’s answer',
    doneConfirmed: 'Confirmed. Thank you: the sender has been told, and the aircraft can go ahead.',
    doneRefused: 'Refused. The sender has been told, and nothing will be published.',
    alreadyConfirmed: 'The club already confirmed this request.',
    alreadyRefused: 'The club already refused this request.',
    notNeeded: 'This request was sent by the club itself: there is nothing to confirm.',
    summary: 'Check these before sending:',
    decisionRequired: 'Choose: confirm or refuse.',
    nameRequired: 'Give your name.',
    roleRequired: 'Give your role in the club.',
    messageTooLong: 'Keep it to 1,000 characters.',
  },

  clubs: {
    eyebrow: 'For flying clubs',
    title: 'Your club’s aircraft, in AéroCheck',
    intro: 'AéroCheck carries flying clubs’ checklists, from the club’s own document. If your aircraft aren’t in it yet (or their checklist has moved on since), send it: one form and a PDF.',
    ctaSend: 'Send a checklist',
    ctaAircraft: 'The aircraft list',
    sections: [
      {
        title: 'What to send',
        items: [
          'The club’s checklist for the aircraft, as a PDF or as photos of its pages (JPEG, PNG or HEIC; up to 4 files, 10 MB each).',
          'The registrations it covers: one request for all the aircraft that share the same document.',
          'In any language: the checklist stays as the club wrote it, whatever the app’s language (English or French).',
          'Not your members’ data: black out names and phone numbers first.',
        ],
      },
      {
        title: 'What your members get',
        body: [
          'The aircraft in the app, with its checklist in 16 phases (from the preflight to the hangar), its speeds and crosswind limits, and the memory test. It is part of AéroCheck Pro, like every aircraft but the WT9 Dynamic: a subscription with a 7-day free trial, or a one-time Lifetime purchase. The club pays nothing and has nothing to run.',
        ],
      },
      {
        title: 'Who sees the document',
        body: [
          'Julien Bono, who develops AéroCheck, prepares the checklist for the app. The document is kept privately while the request is open, and deleted 90 days after it closes: it is never published. What reaches the app is the checklist, for AéroCheck Pro subscribers, who may not redistribute it.',
        ],
        link: { lead: 'The details:', label: 'privacy policy, section 4.3', href: '/privacy#43-aircraft-requests-intakeaerocheckapp' },
      },
      {
        title: 'The club’s confirmation',
        body: [
          'Anyone may send a checklist, but nothing goes live without the club. When the sender says they send it for the club, that is the club’s OK. When a pilot sends it, the club’s contact gets an e-mail with a link to confirm or refuse, with their name and role. A pilot who doesn’t know whom to ask can add the contact later.',
          'A club that would rather write to us directly, or later wants its aircraft out of AéroCheck, writes to the address below.',
        ],
        email: true,
      },
      {
        title: 'When',
        body: [
          'No date is promised: one person prepares the checklists, in their spare time. The request’s page shows where it stands, and the sender gets an e-mail when something needs them, and when it’s live. Before that, they may proofread the draft.',
        ],
      },
      {
        title: 'When the checklist changes',
        body: [
          'Send the new revision the same way: type a registration AéroCheck already has, and the form becomes an update (each aircraft on the aircraft page has an “Outdated?” link for it). Once it is live, every install gets the new version by itself.',
        ],
      },
      {
        title: 'The club’s checklist stays the reference',
        body: [
          'The checklist in AéroCheck is a careful copy of the club’s, but a copy: the club’s approved checklist and the aircraft’s flight manual remain the reference (terms of use, section 1.2).',
        ],
      },
    ],
    emailLead: 'Clubs and questions:',
  },

  aircraft: {
    sendLead: 'Your aircraft isn’t listed, or its checklist is older than the club’s?',
    sendButton: 'Send a checklist',
    clubsButton: 'For flying clubs',
    outdated: 'Outdated?',
    outdatedLabel: '{reg}: outdated? Send the new revision',
  },
};

export type RequestsCopy = typeof en;

const fr: RequestsCopy = {
  common: {
    support: 'Assistance',
    supportHref: '/fr/support',
    retry: 'Réessayer',
    backToForm: 'Retour au formulaire',
    code: 'Code :',
    loading: 'Chargement',
    otherLang: 'This page in English',
    privacyHref: '/fr/privacy',
    termsHref: '/fr/terms',
    clubsHref: '/fr/clubs',
    sendHref: '/fr/send',
    aircraftHref: '/fr/aircraft',
    dash: 'aucun',
  },
  errors: {
    network: 'Le service des demandes ne répond pas. Vérifiez votre connexion et réessayez ; si cela échoue encore, le service est peut-être indisponible pour un moment.',
    invalid_json: 'Le service n’a pas pu lire ce que la page a envoyé. Rechargez la page et réessayez.',
    invalid_field: 'Un des champs n’a pas été accepté : il est signalé dans le formulaire.',
    invalid_registration: 'Ce n’est pas une immatriculation lisible. Tapez-la comme elle est peinte sur l’avion : HB-KFD, F-HVXA, D-EABC.',
    invalid_email: 'Cette adresse e-mail ne semble pas juste.',
    club_contact_is_sender: 'Le contact du club ne peut pas être votre propre adresse : c’est quelqu’un d’autre au club qui confirme. Si c’est vous qui vous occupez des documents du club, envoyez-la « Pour le club ».',
    rights_required: 'Cochez que vous pouvez transmettre ce document.',
    privacy_required: 'Cochez que vous avez lu comment ce que vous envoyez est conservé.',
    too_many_files: 'Jusqu’à 4 fichiers : retirez-en un, puis envoyez à nouveau.',
    bad_type: 'Un des fichiers n’est ni un PDF, ni un JPEG, ni un PNG, ni un HEIC : retirez-le, puis envoyez à nouveau.',
    file_too_large: 'Un des fichiers dépasse 10 Mo : retirez-le, ou envoyez-en une copie plus légère.',
    total_too_large: 'Les fichiers dépassent 25 Mo en tout : retirez-en un, ou envoyez des copies plus légères.',
    unknown_registration: 'AéroCheck n’a pas (ou plus) cette immatriculation : ce ne peut donc pas être une mise à jour. Le formulaire l’envoie maintenant comme un nouvel avion : vérifiez ses détails, puis envoyez à nouveau.',
    known_registration: 'AéroCheck a déjà cette immatriculation : c’est donc une mise à jour. Le formulaire est passé en mise à jour : vérifiez, puis envoyez à nouveau.',
    size_mismatch: 'Un fichier a changé pendant l’envoi (sa taille n’est pas celle que le formulaire a annoncée). Choisissez-le à nouveau, puis envoyez à nouveau.',
    turnstile_failed: 'La vérification anti-robot n’est pas passée. Elle a recommencé : attendez qu’elle se termine, puis envoyez à nouveau.',
    not_found: 'Ce lien n’ouvre rien. Copiez-le à nouveau depuis l’e-mail, en entier (la partie après # compte) ; la demande a aussi pu être close et supprimée.',
    missing_files: 'Tous les fichiers ne sont pas arrivés. Réessayez : ils sont renvoyés.',
    wrong_state: 'Cela a changé entre-temps : la page le montre maintenant tel qu’il est.',
    length_required: 'Votre navigateur a envoyé un fichier sans sa taille, dont le service a besoin. Réessayez avec un autre navigateur (ou une version à jour).',
    payload_too_large: 'Le formulaire est trop long pour le service (les remarques, sans doute). Raccourcissez-le, puis envoyez à nouveau.',
    bad_file: 'Un des fichiers n’est pas ce que son nom annonce (son contenu n’est ni un PDF, ni un JPEG, ni un PNG, ni un HEIC). Retirez-le, puis envoyez à nouveau.',
    rate_limited: 'Trop d’essais depuis votre connexion en peu de temps. Attendez une minute, puis réessayez.',
    internal: 'Le service a rencontré un problème de son côté. Réessayez dans un moment ; si cela continue, écrivez-nous.',
    unavailable: 'Les demandes sont fermées pour le moment (le service n’est pas prêt). Réessayez plus tard : rien n’a été envoyé.',
    daily_cap: 'C’est tout ce que nous pouvons recevoir aujourd’hui. Réessayez demain : rien n’a été envoyé.',
    lookup_unavailable: 'La liste des avions d’AéroCheck ne peut pas être lue pour le moment : impossible de vérifier l’immatriculation. Réessayez dans quelques minutes.',
    forbidden: 'Ce lien n’est pas (ou plus) valable. Copiez-le à nouveau depuis l’e-mail, en entier.',
    unknown: 'Quelque chose s’est mal passé.',
    noToken: 'Cette page s’ouvre avec le lien de votre e-mail (il se termine par #t= et un long code). Ouvrez ce lien à nouveau.',
    uploadGone: 'Cet envoi a expiré (les fichiers attendent 24 heures au plus) ou son lien est faux. Envoyez la demande à nouveau.',
    alreadySent: 'Cette demande a déjà été envoyée : {ticket}. Son lien est dans l’e-mail que nous vous avons envoyé.',
    contactClosed: 'Le contact du club ne peut plus être ajouté (il l’a déjà été, ou la demande a avancé). La page montre maintenant où elle en est.',
    proofClosed: 'Le brouillon n’est plus ouvert à la relecture : la demande a avancé.',
    listChanged: 'La liste des avions d’AéroCheck a changé pendant que vous remplissiez le formulaire. Vérifiez à nouveau l’immatriculation dans quelques minutes, puis envoyez.',
  },
  statuses: {
    uploading: { label: 'Incomplète', line: 'Les fichiers n’ont jamais fini d’arriver : cette demande n’a donc jamais été envoyée.' },
    received: { label: 'Reçue', line: 'Nous avons votre demande et ses fichiers. Nous décidons ensuite si (et quand) nous l’ajoutons.' },
    accepted: { label: 'Acceptée', line: 'La checklist sera ajoutée à AéroCheck.' },
    converting: { label: 'En préparation', line: 'La checklist est en cours de préparation pour AéroCheck.' },
    proofreading: { label: 'Relecture', line: 'Un brouillon est prêt. Jetez-y un œil ci-dessous si vous avez cinq minutes (c’est facultatif).' },
    testflight: { label: 'En test', line: 'La checklist est dans la version de test de l’app. Celle de l’App Store suit.' },
    live: { label: 'Dans l’app', line: 'L’avion est dans AéroCheck, pour les abonnés AéroCheck Pro.' },
    'need-info': { label: 'Infos requises', line: 'Il nous manque quelque chose : voyez le message dans l’historique, et répondez à notre e-mail.' },
    declined: { label: 'Refusée', line: 'Nous n’ajouterons pas celle-ci. La raison est dans l’historique.' },
    duplicate: { label: 'Doublon', line: 'Quelqu’un a déjà demandé cet avion : cette demande-là continue, celle-ci est close.' },
  },
  club: {
    heading: 'L’accord du club',
    states: {
      'not-needed': 'Envoyée pour le club : pas de confirmation nécessaire.',
      pending: 'En attente de la confirmation du club. Rien n’est mis en ligne sans elle.',
      confirmed: 'Le club a confirmé.',
      refused: 'Le club a refusé : cet avion ne sera pas ajouté.',
    },
    addLead: 'Ajoutez le contact du club, et nous lui envoyons le lien pour confirmer.',
    addLabel: 'Le contact du club (e-mail)',
    addHint: 'Une personne qui peut parler pour le club au sujet de ses documents (le président, le chef-instructeur, le responsable technique). Nous lui envoyons un lien pour confirmer ou refuser, rien d’autre.',
    addButton: 'Lui envoyer le lien',
    addDone: 'Envoyé : le contact du club a le lien.',
    addRequired: 'Indiquez le contact du club.',
    addInvalid: 'Cette adresse e-mail ne semble pas juste.',
    addIsSender: 'C’est votre propre adresse : le contact du club est quelqu’un d’autre au club, qui confirme pour lui.',
  },
  kinds: { new: 'Nouvel avion', update: 'Mise à jour de checklist' },
  phases: {
    preflight: 'Pré-vol', beforeEngineStart: 'Avant démarrage', engineStart: 'Démarrage moteur',
    afterEngineStart: 'Après démarrage', taxi: 'Roulage', runup: 'Point fixe', beforeDeparture: 'Avant départ',
    lineUp: 'Alignement', climb: 'Montée', cruise: 'Croisière', descent: 'Descente', approach: 'Approche',
    landing: 'Atterrissage', afterLanding: 'Après atterrissage', shutdown: 'Arrêt moteur', hangar: 'Au hangar',
  },
  units: { kB: 'ko', MB: 'Mo' },

  send: {
    eyebrow: 'Demandes d\'avions',
    title: 'Envoyer la checklist d’un avion',
    intro: 'Votre avion n’est pas dans AéroCheck, ou sa checklist est plus ancienne que celle du club ? Envoyez-nous le document du club : dès que le club confirme, l’avion rejoint l’app (dans AéroCheck Pro, comme tous les avions sauf le WT9).',
    clubsLead: 'Pour les clubs :',
    clubsLink: 'quoi envoyer, qui voit le document, et la confirmation du club',
    stepRegistration: 'L’immatriculation',
    regLabel: 'Immatriculation',
    regHint: 'Telle qu’elle est peinte sur l’avion : HB-KFD, F-HVXA, D-EABC. AéroCheck vérifie s’il l’a déjà.',
    regButton: 'Vérifier',
    regChecking: 'Vérification',
    knownTitle: '{reg} est déjà dans AéroCheck',
    knownBody: 'Ce sera une mise à jour : envoyez la nouvelle révision du club, elle remplacera la checklist de l’app.',
    knownModel: 'Avion',
    knownClub: 'Club',
    knownVersion: 'Version actuelle',
    knownLanguages: 'Langues',
    unknownTitle: '{reg} n’est pas encore dans AéroCheck',
    unknownBody: 'Ce sera un nouvel avion. Dites-nous lequel, et envoyez sa checklist.',
    stepAircraft: 'L’avion',
    otherRegsLabel: 'Autres immatriculations avec la même checklist (facultatif)',
    otherRegsHint: 'Les autres avions du club de ce type, si le même document les couvre : HB-KFI, HB-KFO. Jusqu’à 10 immatriculations en tout.',
    typeLabel: 'Type d’avion',
    typeHint: 'Constructeur et modèle, comme le club l’appelle : Robin DR400/180, Piper PA-28-181.',
    clubLabel: 'Club ou exploitant (facultatif)',
    clubHint: 'Laissez vide pour un avion privé.',
    stepSender: 'Qui l’envoie',
    sendingForLegend: 'Vous l’envoyez',
    forClub: 'Pour le club',
    forClubHint: 'Je m’occupe des documents du club, ou le club m’a demandé de l’envoyer.',
    forSelf: 'En tant que pilote',
    forSelfHint: 'Je le pilote. Le club devra confirmer avant toute mise en ligne.',
    contactLabel: 'Le contact du club (e-mail)',
    contactHint: 'Une personne qui peut parler pour le club au sujet de ses documents (le président, le chef-instructeur, le responsable technique). Nous lui envoyons un lien pour confirmer ou refuser, rien d’autre.',
    contactUnknown: 'Je ne le connais pas : je l’ajouterai plus tard depuis la page de la demande',
    contactUnknownHint: 'La demande attend alors l’accord du club jusqu’à ce que quelqu’un l’ajoute.',
    stepChecklist: 'La checklist',
    filesLabel: 'La checklist du club',
    filesHintNew: 'Un PDF, ou des photos de ses pages (JPEG, PNG ou HEIC) : jusqu’à 4 fichiers, 10 Mo chacun, 25 Mo en tout. Masquez d’abord ce qui est personnel (noms, numéros de téléphone).',
    filesHintUpdate: 'La nouvelle révision, en PDF ou en photos de ses pages (JPEG, PNG ou HEIC) : jusqu’à 4 fichiers, 10 Mo chacun, 25 Mo en tout.',
    filesChoose: 'Choisir des fichiers',
    filesDrop: 'ou déposez-les ici',
    filesRemove: 'Retirer',
    filesRemoveLabel: 'Retirer {name}',
    filesTotal: '{n} fichier(s) sur 4 · {size} sur 25 Mo',
    languagesLegend: 'La langue de la checklist',
    languagesHint: 'La langue dans laquelle le document est écrit. La checklist la garde : elle ne suit pas la langue de l’app (anglais ou français), une checklist en allemand se lit donc en allemand dans les deux.',
    otherLanguageLabel: 'Une autre langue',
    otherLanguageNone: 'Aucune',
    stepYou: 'Vous',
    nameLabel: 'Votre nom (facultatif)',
    nameHint: 'Pour que le club sache qui demande, si on lui demande de confirmer.',
    emailLabel: 'Votre e-mail',
    emailHint: 'Nous vous écrivons à cette adresse au sujet de cette demande (réception, questions, mise en ligne), et de rien d’autre.',
    notesLabel: 'Ce que nous devrions savoir (facultatif)',
    notesHint: 'Quelles pages sont la checklist, ce qui change dans cette révision, un avion qui diffère des autres.',
    counter: '{n} / {max}',
    rightsClub: 'Je peux transmettre ce document à AéroCheck pour le club, et c’est, à ma connaissance, la révision en vigueur du club.',
    rightsSelf: 'Je peux transmettre ce document à AéroCheck, et c’est, à ma connaissance, la révision en vigueur du club. Le club devra confirmer.',
    rightsPrivate: 'L’avion est à moi (ou son propriétaire est d’accord), et je peux transmettre ce document à AéroCheck.',
    rightsMore: 'Ce que cela implique :',
    rightsLink: 'conditions d’utilisation, section 4.0 (en anglais)',
    termsAnchor: '#40-sending-us-an-aircrafts-checklist',
    privacyLabel: 'J’ai lu comment AéroCheck conserve et utilise ce que j’envoie :',
    privacyLink: 'politique de confidentialité, section 4.3',
    privacyAnchor: '#43-demandes-davions-intakeaerocheckapp',
    turnstileLabel: 'Une vérification rapide que vous n’êtes pas un robot',
    turnstileLoading: 'Chargement de la vérification',
    turnstileFailed: 'La vérification n’a pas pu se charger (un bloqueur de contenu, ou Cloudflare injoignable). Rechargez la page pour réessayer.',
    turnstileMissing: 'Attendez la fin de la vérification ci-dessus, puis envoyez.',
    notOpen: 'Les demandes ne sont pas encore ouvertes. Revenez bientôt.',
    submit: 'Envoyer la demande',
    progressSending: 'Envoi de la demande',
    progressUpload: 'Envoi de {i} sur {n} : {name}',
    progressFinishing: 'Finalisation',
    progressLabel: 'Progression de l’envoi',
    uploadStopped: 'L’envoi s’est arrêté sur {name}. Réessayez : les fichiers déjà envoyés restent.',
    summary: 'À vérifier avant d’envoyer :',
    fieldErrors: {
      regRequired: 'Tapez l’immatriculation, puis vérifiez-la.',
      regLookup: 'Vérifiez d’abord l’immatriculation.',
      otherRegsInvalid: 'Ce ne sont pas des immatriculations lisibles : {list}.',
      tooManyRegs: 'Jusqu’à 10 immatriculations en tout.',
      typeRequired: 'Dites de quel avion il s’agit.',
      sendingForRequired: 'Dites si vous l’envoyez pour le club ou en tant que pilote.',
      contactRequired: 'Indiquez le contact du club, ou cochez que vous ne le connaissez pas.',
      contactInvalid: 'Cette adresse e-mail ne semble pas juste.',
      emailRequired: 'Indiquez votre e-mail : c’est là que nous vous disons ce qui se passe.',
      emailInvalid: 'Cette adresse e-mail ne semble pas juste.',
      languagesRequired: 'Choisissez la langue de la checklist.',
      filesRequired: 'Ajoutez la checklist (un PDF ou des photos de ses pages).',
      tooManyFiles: 'Jusqu’à 4 fichiers : retirez-en un d’abord.',
      fileTooBig: '{name} pèse {size} : un fichier peut faire 10 Mo au plus.',
      fileEmpty: '{name} est vide.',
      fileType: '{name} n’est ni un PDF, ni un JPEG, ni un PNG, ni un HEIC.',
      fileContent: '{name} ne ressemble pas au {type} que son nom annonce.',
      fileDuplicate: '{name} est déjà dans la liste.',
      knownOthers: 'À retirer de cette liste : {list} (déjà dans AéroCheck ; une nouvelle révision fait l’objet d’une demande à part).',
      totalTooBig: 'Les fichiers font {size} en tout : 25 Mo au plus.',
      notesTooLong: 'Restez à 1000 caractères.',
      rightsRequired: 'Cochez que vous pouvez transmettre ce document.',
      privacyRequired: 'Cochez que vous avez lu comment ce que vous envoyez est conservé.',
      field: 'Le service ne l’a pas accepté : vérifiez-le.',
      fieldNamed: '{label} : le service ne l’a pas accepté.',
    },
    resultTitle: 'Envoyée : {ticket}',
    resultBody: 'Nous avons votre demande. Ce lien permet de la suivre (nous l’avons aussi envoyé à {email}) : gardez-le, c’est le seul accès.',
    resultLink: 'La page de votre demande',
    resultCopy: 'Copier le lien',
    resultCopied: 'Copié',
    nextTitle: 'La suite',
    nextBody: 'Nous la regardons, puis nous la préparons, ce qui prend le temps qu’il faut (une seule personne, sur son temps libre, sans date promise). Vous recevez un e-mail à chaque étape qui en demande un, et la page montre toujours où elle en est.',
    nextClub: 'Le contact du club a reçu un e-mail lui demandant de confirmer. Rien n’est mis en ligne sans son accord.',
    nextClubNoContact: 'Le club n’a pas encore été sollicité : ajoutez son contact depuis la page de la demande dès que vous l’avez.',
    another: 'Envoyer un autre avion',
  },

  status: {
    eyebrow: 'Demande d\'avion',
    title: 'Votre demande',
    loading: 'Chargement de la demande',
    labelRegistrations: 'Immatriculations',
    labelAircraft: 'Avion',
    labelClub: 'Club',
    labelSent: 'Envoyée le',
    labelUpdated: 'Dernier changement',
    stepsHeading: 'Où elle en est',
    stepDone: 'fait',
    stepCurrent: 'maintenant',
    stepSkipped: 'sautée',
    stepNext: 'à venir',
    historyHeading: 'Historique',
    noTimeline: 'Aucune date n’est promise : une seule personne prépare les checklists, sur son temps libre. Vous recevez un e-mail quand quelque chose dépend de vous, et à la mise en ligne.',
    proofHeading: 'Relire le brouillon (facultatif)',
    proofIntro: 'Voici la checklist telle que l’app l’affichera. Cinq minutes avec le document du club à côté suffisent : chaque phase a-t-elle ses points, dans l’ordre, avec les bonnes valeurs ? C’est un brouillon : ne volez jamais avec.',
    proofLoading: 'Chargement du brouillon',
    proofFailed: 'Le brouillon n’a pas pu être chargé.',
    proofPhases: 'Phases',
    proofSpeeds: 'Vitesses',
    proofSpeedCols: ['Code', 'Description', 'Valeur'],
    proofCrosswind: 'Vent de travers max. : décollage {takeoff}, atterrissage {landing}',
    proofEmptyPhase: 'Rien dans cette phase.',
    proofPage: 'p. {n}',
    proofVersion: 'Version {v}',
    verdictLegend: 'Votre avis',
    verdictOk: 'C’est juste',
    verdictIssue: 'Quelque chose cloche',
    verdictMessage: 'Ce qui cloche, ou une remarque',
    verdictHint: 'Nommez la phase et le point, et ce que dit le document du club à la place.',
    verdictRequired: 'Dites ce qui cloche : la phase, le point, et ce que dit le document.',
    verdictTooLong: 'Restez à 2000 caractères.',
    verdictThanksOk: 'Merci : noté comme juste.',
    verdictThanksIssue: 'Merci : nous allons regarder et corriger le brouillon.',
    proofYours: 'Votre avis jusqu’ici : {verdict}. Envoyez-en un autre ci-dessous si quelque chose change.',
    eventClub: {
      pending: 'Le club a été sollicité',
      confirmed: 'Le club a confirmé',
      refused: 'Le club a refusé',
      'not-needed': 'Pas de confirmation nécessaire du club',
    },
    eventProofread: {
      ok: 'Votre relecture : c’est juste',
      issue: 'Votre relecture : quelque chose cloche',
    },
  },

  confirm: {
    eyebrow: 'Clubs',
    title: 'Confirmer une demande de checklist',
    loading: 'Chargement de la demande',
    intro: '{sender} demande d’ajouter à AéroCheck la checklist de votre club, {club}, pour les avions ci-dessous. En tant que personne pouvant parler pour le club, c’est vous qui décidez si elle va de l’avant.',
    introNoClub: '{sender} demande d’ajouter cette checklist à AéroCheck pour les avions ci-dessous. En tant que personne pouvant parler pour le club, c’est vous qui décidez si elle va de l’avant.',
    senderUnknown: 'Un pilote',
    labelTicket: 'Demande',
    labelKind: 'Objet',
    labelRegistrations: 'Immatriculations',
    labelAircraft: 'Avion',
    labelClub: 'Club',
    labelLanguages: 'Langue de la checklist',
    labelSent: 'Envoyée le',
    whatTitle: 'Ce que confirmer implique',
    what: [
      'AéroCheck peut ajouter la checklist du club pour ces avions à l’app, dans AéroCheck Pro (comme tous les avions sauf le WT9, gratuit).',
      'Le document lui-même n’est jamais publié : il sert uniquement à préparer la checklist, et il est supprimé 90 jours après la clôture de la demande.',
      'Dans l’app, la checklist approuvée du club reste la référence.',
      'Si le club veut plus tard la retirer, il nous l’écrit.',
    ],
    refuseBody: 'Refuser clôt l’affaire : rien n’est publié, et l’expéditeur en est informé.',
    moreLead: 'Plus d’informations pour les clubs :',
    moreLink: 'aerocheck.app/fr/clubs',
    decisionLegend: 'La réponse du club',
    confirm: 'Confirmer : AéroCheck peut l’ajouter',
    refuse: 'Refuser : ne pas l’ajouter',
    nameLabel: 'Votre nom',
    roleLabel: 'Votre fonction au club',
    roleHint: 'Président, chef-instructeur, responsable technique, secrétaire.',
    messageLabel: 'Un message pour l’expéditeur et pour nous (facultatif)',
    statement: 'En répondant, vous déclarez pouvoir parler pour le club à ce sujet.',
    submit: 'Envoyer la réponse du club',
    doneConfirmed: 'Confirmé. Merci : l’expéditeur en est informé, et l’avion peut aller de l’avant.',
    doneRefused: 'Refusé. L’expéditeur en est informé, et rien ne sera publié.',
    alreadyConfirmed: 'Le club a déjà confirmé cette demande.',
    alreadyRefused: 'Le club a déjà refusé cette demande.',
    notNeeded: 'Cette demande a été envoyée par le club lui-même : il n’y a rien à confirmer.',
    summary: 'À vérifier avant d’envoyer :',
    decisionRequired: 'Choisissez : confirmer ou refuser.',
    nameRequired: 'Indiquez votre nom.',
    roleRequired: 'Indiquez votre fonction au club.',
    messageTooLong: 'Restez à 1000 caractères.',
  },

  clubs: {
    eyebrow: 'Pour les clubs',
    title: 'Les avions de votre club, dans AéroCheck',
    intro: 'AéroCheck contient des checklists de clubs, tirées du document du club. Si vos avions n’y sont pas encore (ou si leur checklist a changé depuis), envoyez-la : un formulaire et un PDF.',
    ctaSend: 'Envoyer une checklist',
    ctaAircraft: 'La liste des aéronefs',
    sections: [
      {
        title: 'Quoi envoyer',
        items: [
          'La checklist du club pour l’avion, en PDF ou en photos de ses pages (JPEG, PNG ou HEIC ; jusqu’à 4 fichiers, 10 Mo chacun).',
          'Les immatriculations qu’elle couvre : une seule demande pour tous les avions qui partagent le même document.',
          'Dans n’importe quelle langue : la checklist reste telle que le club l’a écrite, quelle que soit la langue de l’app (anglais ou français).',
          'Pas les données de vos membres : masquez d’abord les noms et les numéros de téléphone.',
        ],
      },
      {
        title: 'Ce que vos membres y gagnent',
        body: [
          'L’avion dans l’app, avec sa checklist en 16 phases (du pré-vol au hangar), ses vitesses et ses limites de vent de travers, et le test de mémoire. Il fait partie d’AéroCheck Pro, comme tous les avions sauf le WT9 Dynamic : un abonnement avec 7 jours d’essai gratuit, ou un achat unique Lifetime. Le club ne paie rien et n’a rien à gérer.',
        ],
      },
      {
        title: 'Qui voit le document',
        body: [
          'Julien Bono, qui développe AéroCheck, prépare la checklist pour l’app. Le document est conservé de façon privée tant que la demande est ouverte, et supprimé 90 jours après sa clôture : il n’est jamais publié. Ce qui arrive dans l’app, c’est la checklist, pour les abonnés AéroCheck Pro, qui ne peuvent pas la redistribuer.',
        ],
        link: { lead: 'Le détail :', label: 'politique de confidentialité, section 4.3', href: '/fr/privacy#43-demandes-davions-intakeaerocheckapp' },
      },
      {
        title: 'La confirmation du club',
        body: [
          'Tout le monde peut envoyer une checklist, mais rien n’est mis en ligne sans le club. Quand l’expéditeur dit l’envoyer pour le club, c’est l’accord du club. Quand un pilote l’envoie, le contact du club reçoit un e-mail avec un lien pour confirmer ou refuser, avec son nom et sa fonction. Un pilote qui ne sait pas à qui demander peut ajouter le contact plus tard.',
          'Un club qui préfère nous écrire directement, ou qui veut plus tard retirer ses avions d’AéroCheck, écrit à l’adresse ci-dessous.',
        ],
        email: true,
      },
      {
        title: 'Quand',
        body: [
          'Aucune date n’est promise : une seule personne prépare les checklists, sur son temps libre. La page de la demande montre où elle en est, et l’expéditeur reçoit un e-mail quand quelque chose dépend de lui, et à la mise en ligne. Avant cela, il peut relire le brouillon.',
        ],
      },
      {
        title: 'Quand la checklist change',
        body: [
          'Envoyez la nouvelle révision de la même façon : tapez une immatriculation qu’AéroCheck a déjà, et le formulaire devient une mise à jour (chaque avion de la page des aéronefs a un lien « Pas à jour ? » pour cela). Une fois en ligne, chaque installation reçoit la nouvelle version d’elle-même.',
        ],
      },
      {
        title: 'La checklist du club reste la référence',
        body: [
          'La checklist d’AéroCheck est une copie soignée de celle du club, mais une copie : la checklist approuvée du club et le manuel de vol de l’avion restent la référence (conditions d’utilisation, section 1.2).',
        ],
      },
    ],
    emailLead: 'Clubs et questions :',
  },

  aircraft: {
    sendLead: 'Votre avion n’y est pas, ou sa checklist est plus ancienne que celle du club ?',
    sendButton: 'Envoyer une checklist',
    clubsButton: 'Pour les clubs',
    outdated: 'Pas à jour ?',
    outdatedLabel: '{reg} : pas à jour ? Envoyer la nouvelle révision',
  },
};

/**
 * French spacing, applied once: the space before ? ! : ; and inside « » becomes a no-break space,
 * so a phone never starts a line with a lone "?" or ":". The strings above stay readable with
 * ordinary spaces, like the rest of the site's French.
 */
function frenchSpacing<T>(value: T): T {
  if (typeof value === 'string') return value.replace(/ ([?!:;»])/g, '\u00a0$1').replace(/« /g, '«\u00a0') as unknown as T;
  if (Array.isArray(value)) return value.map(frenchSpacing) as unknown as T;
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, frenchSpacing(v)])) as T;
  }
  return value;
}

export const REQUESTS_COPY: Record<Lang, RequestsCopy> = { en, fr: frenchSpacing(fr) };

/** A language code as its name in the page's language ("de" → "German" / "Allemand"). */
export function languageName(code: string, lang: Lang): string {
  try {
    const name = new Intl.DisplayNames([lang], { type: 'language' }).of(code) ?? code;
    return name.charAt(0).toLocaleUpperCase(lang) + name.slice(1);
  } catch {
    return code.toUpperCase();
  }
}

/** Serialised for a `<script type="application/json">`: no `</script>` can close it early. */
export function toJsonScript(value: unknown): string {
  return JSON.stringify(value).replace(/</g, '\\u003c');
}
